#!/bin/bash
#     ____  _____ ______
#    / __ \/ ___// ____/	script by Dennis Chaves
#   / / / /\__ \/ /    		github.com/ismashbuttons 
#  / /_/ /___/ / /___  		dencha@airmail.cc 
# /_____//____/\____/   
#                       
# ref - Open a PDF from the reference library (reflib)
#       Simple!

cd ~/Documents/reflib/ && ls *.pdf | dmenu -b -p 'select a document: ' -l 20 | xargs -r zathura &
